/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("HeaderListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheHeaderList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheHeaderList.onFilterBar().iCheckFilterField("Plant");
            Then.onTheHeaderList.onFilterBar().iCheckFilterField("Inspection Lot");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheHeaderList.onTable().iCheckColumns(undefined, {"Plant":{"header":"Plant"},"InspectionLot":{"header":"Inspection Lot"},"ProductCode":{"header":"Material"},"Product":{"header":"Object Short Text"},"BatchNo":{"header":"Batch"},"BatchSize":{"header":"Inspection Lot Quantity"},"BatchSizeUnit":{"header":"Base Unit of Measure"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheHeaderList.onFilterBar().iExecuteSearch();
            
            Then.onTheHeaderList.onTable().iCheckRows();

            When.onTheHeaderList.onTable().iPressRow(0);
            Then.onTheHeaderObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});